### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by Spearman17** [tmpethick/anki-onenote-importer#7]
I am getting this error message:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons\onenote_importer\__init__.py", line 66, in importMHT
    output = parser.run()
  File "C:\Users\User\AppData\Roaming\Anki2\addons\onenote_importer\parser.py", line 70, in run
    for row in table.findAll('tr', recursive=False):
AttributeError: 'NoneType' object has no attribute 'findAll'

**Comment by Ziinc** [comment]
It could be that there are no tables found.
